name: spell checking
on:
  push:
    branches:
      - main
      - 'fork-2026-08'
  pull_request:
    branches:
      - main
      - 'fork-2026-08'

permissions: {}

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: typos-action
      uses: crate-ci/typos@512fc24f32f44ab01972217aaaf3dc86ec234d53 # v1.50.2

