name: test

on:
  push:
    branches:
      - main
      - 'fork-2026-08'
  pull_request:
    branches:
      - main
      - 'fork-2026-08'

jobs:
  build:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: ['macos-latest', 'windows-latest', 'ubuntu-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: make test
